import Image from 'next/image';
import Link from 'next/link';

export const metadata = {
  title: 'Terms & Conditions - Mr Shomser',
  description: 'Terms and conditions for using Mr Shomser AI assistant',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-950 dark:to-gray-900">
      <div className="max-w-4xl mx-auto px-4 py-12">
        {/* Header */}
        <div className="text-center mb-12">
          <Link href="/" className="inline-block mb-6">
            <Image
              src="/logo.svg"
              alt="Mr Shomser"
              width={80}
              height={80}
              className="mx-auto"
            />
          </Link>
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
            Terms & Conditions
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-400">
            Last updated: March 23, 2026
          </p>
        </div>

        {/* Content */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-8 mb-8">
          <div className="prose dark:prose-invert max-w-none">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              1. Acceptance of Terms
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-6">
              By accessing and using Mr Shomser ("the Service"), you accept and agree to be bound by the terms 
              and provision of this agreement. If you do not agree to these terms, please do not use the Service.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              2. Use of Service
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              Mr Shomser is provided as-is for informational and educational purposes. The Service includes:
            </p>
            <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mb-6 space-y-2">
              <li>AI-powered chat assistance</li>
              <li>Programming and technical guidance</li>
              <li>General information and learning resources</li>
              <li>Local storage of chat history in your browser</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              3. User Responsibilities
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-4">
              You agree to:
            </p>
            <ul className="list-disc list-inside text-gray-700 dark:text-gray-300 mb-6 space-y-2">
              <li>Use the Service lawfully and responsibly</li>
              <li>Not attempt to exploit, harm, or disrupt the Service</li>
              <li>Not use the Service for illegal activities</li>
              <li>Not share harmful, offensive, or inappropriate content</li>
              <li>Respect the privacy and rights of others</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              4. AI-Generated Content
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-6">
              The responses provided by Mr Shomser are generated by AI and should not be considered as professional 
              advice. Always verify important information from reliable sources. We are not responsible for any 
              decisions made based on AI-generated responses.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              5. Privacy & Data Storage
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-6">
              Your chat conversations are stored locally in your browser and on our database for 30 days. 
              We use a self-hosted AI model, meaning your conversations are processed locally and not sent to 
              third-party AI services. See our Privacy Policy for more details.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              6. Intellectual Property
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-6">
              The Service, including its design, code, and branding, is owned by the developer. 
              You may not copy, modify, or distribute any part of the Service without permission.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              7. Disclaimer of Warranties
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-6">
              The Service is provided "as is" without warranties of any kind, either express or implied. 
              We do not guarantee that the Service will be uninterrupted, secure, or error-free.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              8. Limitation of Liability
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-6">
              In no event shall Mr Shomser or its developer be liable for any indirect, incidental, special, 
              consequential, or punitive damages resulting from your use of or inability to use the Service.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              9. Changes to Terms
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-6">
              We reserve the right to modify these terms at any time. Changes will be effective immediately 
              upon posting. Your continued use of the Service constitutes acceptance of the modified terms.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
              10. Contact Information
            </h2>
            <p className="text-gray-700 dark:text-gray-300 mb-6">
              If you have any questions about these Terms & Conditions, please contact us at:
              <br />
              <a href="mailto:anup04sust@gmail.com" className="text-blue-600 dark:text-blue-400 hover:underline">
                anup04sust@gmail.com
              </a>
            </p>
          </div>
        </div>

        {/* Back to Home */}
        <div className="text-center mt-8">
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white rounded-lg transition-all duration-200 hover:scale-105"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Chat
          </Link>
        </div>
      </div>
    </div>
  );
}
